### ISSUE TITLE
MacOS Sonoma Support

### ISSUE THREAD

**Issue by benwwalker1** [aydenp/FocusPlsNoBadges#9]
Building the project on Sonoma 14.0, I get the following error:

`FocusPlsNoBadges/ModelFiles+Current.swift:15: Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=NSCocoaErrorDomain Code=257 "The file “Assertions.json” couldn’t be opened because you don’t have permission to view it." UserInfo={NSFilePath=/Users/benwalker/Library/DoNotDisturb/DB/Assertions.json, NSUnderlyingError=0x600003f2c000 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}`

I'm not sure if this is a global problem or just one on my local machine. I've tried changing the file's permissions but nothing's been working. Feel free to close this immediately if it's not reproducible.

Thanks!

**Comment by jackmeehan** [comment]
> Building the project on Sonoma 14.0, I get the following error:
> 
> `FocusPlsNoBadges/ModelFiles+Current.swift:15: Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=NSCocoaErrorDomain Code=257 "The file “Assertions.json” couldn’t be opened because you don’t have permission to view it." UserInfo={NSFilePath=/Users/benwalker/Library/DoNotDisturb/DB/Assertions.json, NSUnderlyingError=0x600003f2c000 {Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted"}}`
> 
> I'm not sure if this is a global problem or just one on my local machine. I've tried changing the file's permissions but nothing's been working. Feel free to close this immediately if it's not reproducible.
> 
> Thanks!

Hey, this is resolved by enabling Full Disk Access for the app as per [this comment](https://github.com/aydenp/FocusPlsNoBadges/issues/8#issue-1443856998)

**Comment by benwwalker1** [comment]
Thanks so much! Sorry to open a new issue, will close it now.
